spring:
  ssl:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_olam
    username: postgres
    password: 11111111
  jpa:
    hibernate:
      ddl-auto: create
      format_sql: true
    show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  application:
    name: smart_olam
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

image:
  upload-dir: uploads/images


